version: "3"

services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
    networks:
      - back-tier

  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    networks:
      - back-tier

  schema-registry:
    image: confluent/schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
    - "8081:8081"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
    networks:
      - back-tier

  rest-proxy:
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
    - "8082:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    networks:
      - back-tier

  landoop:
    image: landoop/kafka-topics-ui
    depends_on:
      - rest-proxy
    ports:
    - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
      PROXY: "true"
    networks:
      - back-tier

networks:
  back-tier: